let data = { body: [{
    _cdpColorUrl: '/en-us/paint-colors/color/152/florida-orange',
    number: '152',
    name: 'Florida Orange',
    family: 'Orange',
    familyURL: null,
    hex: 'FDC983',
    contrastColor: 'dark',
    toolURL: '/152/florida-orange',
    cdpColorUrl: '/en-us/paint-colors/color/152/florida-orange',
    exteriorAvailability: 'not recommended',
    wetSampleSKU: 'ZWB100000001428312',
    drySampleSKU: 'M94300631TL-152',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/153/fresh-fruit',
    number: '153',
    name: 'Fresh Fruit',
    family: 'Orange',
    familyURL: null,
    hex: 'FEC478',
    contrastColor: 'dark',
    toolURL: '/153/fresh-fruit',
    cdpColorUrl: '/en-us/paint-colors/color/153/fresh-fruit',
    exteriorAvailability: 'not recommended',
    wetSampleSKU: 'ZWB100000001431199',
    drySampleSKU: 'M94300632TL-153',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/154/mango-punch',
    number: '154',
    name: 'Mango Punch',
    family: 'Orange',
    familyURL: null,
    hex: 'FFA84E',
    contrastColor: 'dark',
    toolURL: '/154/mango-punch',
    cdpColorUrl: '/en-us/paint-colors/color/154/mango-punch',
    exteriorAvailability: 'unavailable',
    wetSampleSKU: 'ZWB100000001429323',
    drySampleSKU: 'M94300633TL-154',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/155/point-pleasant',
    number: '155',
    name: 'Point Pleasant',
    family: 'Orange',
    familyURL: null,
    hex: 'F5E8CE',
    contrastColor: 'dark',
    toolURL: '/155/point-pleasant',
    cdpColorUrl: '/en-us/paint-colors/color/155/point-pleasant',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001429334',
    drySampleSKU: 'M94300634TL-155',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/156/sweet-nectar',
    number: '156',
    name: 'Sweet Nectar',
    family: 'Orange',
    familyURL: null,
    hex: 'FDE0B5',
    contrastColor: 'dark',
    toolURL: '/156/sweet-nectar',
    cdpColorUrl: '/en-us/paint-colors/color/156/sweet-nectar',
    exteriorAvailability: 'not recommended',
    wetSampleSKU: 'ZWB100000001430100',
    drySampleSKU: 'M94300635TL-156',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/157/cantaloupe',
    number: '157',
    name: 'Cantaloupe',
    family: 'Orange',
    familyURL: null,
    hex: 'FEDBAE',
    contrastColor: 'dark',
    toolURL: '/157/cantaloupe',
    cdpColorUrl: '/en-us/paint-colors/color/157/cantaloupe',
    exteriorAvailability: 'not recommended',
    wetSampleSKU: 'ZWB100000001430111',
    drySampleSKU: 'M94300636TL-157',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/158/pineapple-orange',
    number: '158',
    name: 'Pineapple Orange',
    family: 'Orange',
    familyURL: null,
    hex: 'FAD4A4',
    contrastColor: 'dark',
    toolURL: '/158/pineapple-orange',
    cdpColorUrl: '/en-us/paint-colors/color/158/pineapple-orange',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001430489',
    drySampleSKU: 'M94300637TL-158',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/159/peach-crisp',
    number: '159',
    name: 'Peach Crisp',
    family: 'Orange',
    familyURL: null,
    hex: 'F5C382',
    contrastColor: 'dark',
    toolURL: '/159/peach-crisp',
    cdpColorUrl: '/en-us/paint-colors/color/159/peach-crisp',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001430951',
    drySampleSKU: 'M94300638TL-159',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/160/soft-marigold',
    number: '160',
    name: 'Soft Marigold',
    family: 'Orange',
    familyURL: null,
    hex: 'F0BA77',
    contrastColor: 'dark',
    toolURL: '/160/soft-marigold',
    cdpColorUrl: '/en-us/paint-colors/color/160/soft-marigold',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001430962',
    drySampleSKU: 'M94300639TL-160',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/161/brilliant-amber',
    number: '161',
    name: 'Brilliant Amber',
    family: 'Orange',
    familyURL: null,
    hex: 'E39A50',
    contrastColor: 'dark',
    toolURL: '/161/brilliant-amber',
    cdpColorUrl: '/en-us/paint-colors/color/161/brilliant-amber',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001429091',
    drySampleSKU: 'M94300640TL-161',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/162/corinthian-white',
    number: '162',
    name: 'Corinthian White',
    family: 'Yellow',
    familyURL: null,
    hex: 'F6EACA',
    contrastColor: 'dark',
    toolURL: '/162/corinthian-white',
    cdpColorUrl: '/en-us/paint-colors/color/162/corinthian-white',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001429102',
    drySampleSKU: 'M94300641TL-162',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/163/somerset-peach',
    number: '163',
    name: 'Somerset Peach',
    family: 'Orange',
    familyURL: null,
    hex: 'F7E3BF',
    contrastColor: 'dark',
    toolURL: '/163/somerset-peach',
    cdpColorUrl: '/en-us/paint-colors/color/163/somerset-peach',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001428929',
    drySampleSKU: 'M94300642TL-163',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/164/birmingham-cream',
    number: '164',
    name: 'Birmingham Cream',
    family: 'Orange',
    familyURL: null,
    hex: 'F5DBB0',
    contrastColor: 'dark',
    toolURL: '/164/birmingham-cream',
    cdpColorUrl: '/en-us/paint-colors/color/164/birmingham-cream',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001428940',
    drySampleSKU: 'M94300643TL-164',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/165/glowing-apricot',
    number: '165',
    name: 'Glowing Apricot',
    family: 'Yellow',
    familyURL: null,
    hex: 'F3CF9C',
    contrastColor: 'dark',
    toolURL: '/165/glowing-apricot',
    cdpColorUrl: '/en-us/paint-colors/color/165/glowing-apricot',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001428571',
    drySampleSKU: 'M94300644TL-165',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/166/orange-ice',
    number: '166',
    name: 'Orange Ice',
    family: 'Orange',
    familyURL: null,
    hex: 'EBBC7F',
    contrastColor: 'dark',
    toolURL: '/166/orange-ice',
    cdpColorUrl: '/en-us/paint-colors/color/166/orange-ice',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001430779',
    drySampleSKU: 'M94300645TL-166',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/167/old-gold',
    number: '167',
    name: 'Old Gold',
    family: 'Orange',
    familyURL: null,
    hex: 'E1A863',
    contrastColor: 'dark',
    toolURL: '/167/old-gold',
    cdpColorUrl: '/en-us/paint-colors/color/167/old-gold',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001431415',
    drySampleSKU: 'M94300646TL-167',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/168/amber',
    number: '168',
    name: 'Amber',
    family: 'Orange',
    familyURL: null,
    hex: 'C58240',
    contrastColor: 'dark',
    toolURL: '/168/amber',
    cdpColorUrl: '/en-us/paint-colors/color/168/amber',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001431306',
    drySampleSKU: 'M94300647TL-168',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/169/aura',
    number: '169',
    name: 'Aura',
    family: 'Yellow',
    familyURL: null,
    hex: 'F7E7C5',
    contrastColor: 'dark',
    toolURL: '/169/aura',
    cdpColorUrl: '/en-us/paint-colors/color/169/aura',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001431308',
    drySampleSKU: 'M94300648TL-169',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  },
  {
    _cdpColorUrl: '/en-us/paint-colors/color/170/traditional-yellow',
    number: '170',
    name: 'Traditional Yellow',
    family: 'Yellow',
    familyURL: null,
    hex: 'F6E1AA',
    contrastColor: 'dark',
    toolURL: '/170/traditional-yellow',
    cdpColorUrl: '/en-us/paint-colors/color/170/traditional-yellow',
    exteriorAvailability: 'available',
    wetSampleSKU: 'ZWB100000001431309',
    drySampleSKU: 'M94300649TL-170',
    eStoreAvailable: true,
    isColorAndStain: false,
    productTypesAvailable: 'paint',
    isStainType: false,
    stainProperties: null,
    defaultStainType: null
  }]
}

module.exports = {
    data
}